Feature
cgcarlosg/Design-Teardown-Project pull request #1
Opened 2020-10-16 02:47 UTC by cgcarlosg

initial pull request to run linters by first time

2020-10-20 00:15 UTC, umairarshadbutt reviewed
# Status: REQUIRED CHANGES :warning: :construction: 

Hi 
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.

- [ ] Change footer menus to `<ul>` with `<li>`. This is more semantic than the `<div>`. See inline comments
- [ ] Remove the horizontal scroll bar (You can visit [image](https://user-images.githubusercontent.com/29689273/96524833-c126c200-1292-11eb-9a18-1d05de534b7c.png) or [video](https://www.awesomescreenshot.com/video/1411018?key=2e51768e8232e9b8e6d96786d71bdc59))
- [ ] **[OPTIONAL]** Use the navbar tag (`nav`) for navbar

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-10-20 00:15 UTC, umairarshadbutt commented on index.html
> +        </div>
A better approach is using `<ul>` and `<li>`
Please add centered links in `<li>`

2020-10-20 16:29 UTC, Temmarie requested changes
### Changes Required! :recycle: 
Hi @cgcarlosg ! 
### You have done well so far :clap: However, you did not finish all the previous review changes. Kindly work on them and submit them for another code review.

Your project looks great. However, your project cannot be approved until you write a descriptive PR Message. It's essential that your repository is professional, as this is one of the things that potential colleagues will look at when recruiting team members. Please refer to [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more information.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Crace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2020-10-20 17:12 UTC, Temmarie approved these changes
## Status: Approved ✔️  

### Hi @cgcarlosg!  

### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: 🎉 

### You may merge, good luck with your next projects! :rocket: 
### Happy Coding! 👍 
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2020-10-30 12:42 UTC, cgcarlosg commented
project completed

2020-10-30 12:43 UTC, closed without merging